"""empty message

Revision ID: 26d1e79fbd6f
Revises: f179f69c15e3
Create Date: 2025-10-27 18:34:39.517718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d1e79fbd6f'
down_revision = 'f179f69c15e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titleName', sa.String(length=80), nullable=False),
    sa.Column('reviewNote', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_constraint('tasks_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'])
        batch_op.drop_column('title')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('task_id')

    op.drop_table('titles')
    # ### end Alembic commands ###
