"""empty message

Revision ID: 4be4776daf18
Revises: c329d81da174
Create Date: 2025-10-30 21:19:54.171457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be4776daf18'
down_revision = 'c329d81da174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_title_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'titles', ['title_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_constraint('titles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('titles_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_title_id_fkey', 'titles', ['title_id'], ['id'])

    # ### end Alembic commands ###
