"""empty message

Revision ID: 805557506317
Revises: 26d1e79fbd6f
Create Date: 2025-10-27 23:09:41.704802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805557506317'
down_revision = '26d1e79fbd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.alter_column('reviewNote',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.alter_column('reviewNote',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
