"""empty message

Revision ID: c329d81da174
Revises: 805557506317
Create Date: 2025-10-28 18:26:36.833538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c329d81da174'
down_revision = '805557506317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('tasks_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'titles', ['title_id'], ['id'])
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_task_id_fkey', 'tasks', ['task_id'], ['id'])
        batch_op.drop_column('title_id')

    # ### end Alembic commands ###
