"""empty message

Revision ID: f179f69c15e3
Revises: 6f1fce31eca3
Create Date: 2025-10-27 14:25:44.319969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f179f69c15e3'
down_revision = '6f1fce31eca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
